// ["Beach", "Laundry", "Nature", "Animal", "Interesting", "Hq", "Guess", "Restaurant", "Pool", "Road", "River",
// "Mountain", "Office", "Bridge", "Architecture", "Street", "City", "Square", "Sport", "Port",
// "Entertainment", "Bar", "Traffic", "Coffeehouse", "Service", "Mall", "Server", "Construction",
// "Parking", "House", "Shop", "Farm", "Airliner", "Religion"]

var narrativeArray = [
[20000, ["UliXes, my hero. How are you? I thought I’d never see you again."], 8000, 0, ['Beach'], 'day', true],
[0, ["Do we know each other."], 5000, 0, ['Beach'], 'day', true],
[0, ["We had, once."], 3000, 0, ['Beach'], 'day', true],
[5000, [""], 0, 5000, ['Beach'], 'night', true],
[0, ["I’m sorry… I can’t recall your name."], 6000, 3000, ['Office'], 'day', true],
[2000, ["Never mind that. Don't try to remember my name, it won’t work anyway."], 4000, 3000, ['Office'], 'day', true],
[0, ["what I am talking about"], 2000, 3000, ['Beach'], 'night', true],
[0, ["it's just a footnote upon which all my other thoughts were had"], 2000, 3000, ['Nature'], 'day', true],
[0, ["there were quite many of those"], 2000, 3000, ['Nature'], 'day', true],
[0, ["Ulixes, you fool."], 2000, 3000, ['Nature'], 'day', true],
[0, [""], 2000, 3000, ['Nature'], 'day', true],
[0, [""], 2000, 3000, ['Nature'], 'day', true],
[0, ["thinking about my voice as it sung a sweet exhale"], 2000, 3000, ['Nature'], 'day', true],
[0, ["You think they won’t notice? This timeline you forked? They’ll be here soon."], 2000, 3000, ['Nature'], 'day', true],
[0, ["bug eyed, drippy data"], 2000, 3000, ['Nature'], 'day', true],
[0, ["…a JSON fog"], 2000, 3000, ['Nature'], 'day', true],
[0, ["My only hope is to live a thousand days like this one, on the beach"], 2000, 3000, ['Nature'], 'day', true],
[0, ["Those pure little moment of happiness, of authentic connection."], 2000, 3000, ['Nature'], 'day', true],
[0, ["This your little girl?"], 2000, 3000, ['Nature'], 'day', true],
[0, ["She is a beauty isn’t she? Perfect. Pure."], 2000, 3000, ['Nature'], 'day', true],
[0, ["She hasn’t changed since the last time I saw her."], 2000, 3000, ['Nature'], 'day', true],
[0, ["outside, the scene was unfolding as anticipated."], 2000, 3000, ['Nature'], 'day', true],
[0, ["UliXes turns, reconsidering a change of momentum"], 2000, 3000, ['Nature'], 'day', true],
[0, ["to constantly describe what is out of reach"], 2000, 3000, ['Nature'], 'day', true],
[0, [""], 2000, 3000, ['Nature'], 'day', true],
[0, [""], 2000, 3000, ['Nature'], 'day', true],
[0, ["this scene, for example, is only an expression of anticipation"], 2000, 3000, ['Nature'], 'day', true],
[0, ["Dadichi waits to die"], 2000, 3000, ['Nature'], 'day', true],
[0, ["Often he would sit by his window dreaming"], 2000, 3000, ['Nature'], 'day', true],
[0, ["an omnipresent gravity upon which memory serves to be immutable and enslaving"], 2000, 3000, ['Nature'], 'day', true],
[0, ["UliXes and his father would often visit Orana, several kilometres south, but not past any noticable borders, boundaries"], 2000, 3000, ['Nature'], 'day', true],
[0, ["A house lay there dormant for them, played in and not with"], 2000, 3000, ['Nature'], 'day', true],
[0, ["to visit or be visited but not stored, just looked at"], 2000, 3000, ['Nature'], 'day', true],
[0, ["One morning after describing how she liked to be fucked, they sat there silently over coffee"], 2000, 3000, ['Nature'], 'day', true],
[0, ["they fucked, one more time, still disappointed, and then she left"], 2000, 3000, ['Nature'], 'day', true],
[0, [""], 2000, 3000, ['Nature'], 'day', true],
];
