var narrativeArray = [
     [600, ['wow jellyfish are crazy'], 100, ['Office'], 'day', true],
      [200, ['they’re literally going to take over'], 100, ['Office'], 'day', true],
      [100, ['the ocean apparently'], 100, ['Office'], 'day', true],
      [200, ['there were hundreds of bluebottles'], 100, ['Office'], 'day', true],
      [100, ['washed up on Marley beach'], 0, ['Office'], 'day', true],
      [400, ['Yeah wow'], 100, ['Office'], 'day', true],
      [200, ['one of not many animals that will flourish'], 100, ['Office'], 'day', true],
      [200, ['cool, leave it to them'], 100, ['Office'], 'day', true],
      [00, ['the world that is'], 100, ['Office'], 'day', true],
      [200, ['get used to seeing sea creatures'], 100, ['Office'], 'day', true],
      [100, ['in traditionally dry spaces'], 100, ['Office'], 'day', true],
      [400, ['Octopuses apparently'], 100, ['Office'], 'day', true],
      [50, ['are starting to hunt collaboratively'], 100, ['Office'], 'day', true],
      [0, ['in the Mediterranean because'], 100, ['Office'], 'day', true],
      [0, ['foods so scarce'], 100, ['Office'], 'day', true],
      [0, ['Hey I have to go because'], 100, ['Office'], 'day', true],
      [50, ['rainbow fell off her chair'], 100, ['Office'], 'day', true],
      [50, ['And there’s blood everywhere'], 100, ['Office'], 'day', true],
    ];
