var narrativeArray = [
     [600, ['you go first!'], 100, ['Office'], 'day', true],
      [400, ['no you go first!'], 100, ['Office'], 'day', true],
      [100, ['no you go first!!'], 100, ['Office'], 'day', true],
      [2000, ['you go first!!'], 100, ['Office'], 'day', true],
      [300, ['nooo. you go first!'], 0, ['Office'], 'day', true],
      [400, ['you!!'], 100, ['Office'], 'day', true],
      [200, ['no you!'], 100, ['Office'], 'day', true],
      [00, ['you go first!!!'], 100, ['Office'], 'day', true],
      [00, ['go first!!!'], 100, ['Office'], 'day', true],
      [1000, ['no you go first!!!!!!'], 100, ['Office'], 'day', true],
      [600, ['no you go first!!!'], 100, ['Office'], 'day', true],
      [400, ['i will if you go first!'], 100, ['Office'], 'day', true],
      [100, ['no fucking way, you go first!'], 100, ['Office'], 'day', true],
      [0, ['NO you go first and fuck you!'], 100, ['Office'], 'day', true],
      [0, ['you'], 100, ['Office'], 'day', true],
      [0, ['you..'], 100, ['Office'], 'day', true],
      [1000, ['YOU!!'], 100, ['Office'], 'day', true],
      [1000, ['...'], 100, ['Office'], 'day', true],
    ];
